name: GemsEconomy
version: 2.6
main: me.xanium.gemseconomy.GemsCore
author: Xanium
description: An custom economy plugin for spigot servers.
website: https://www.spigotmc.org/resources/gemseconomy.19655/
softdepend: [Vault]
commands:
  gbalance:
    usage: /gbalance (player)
    aliases: [bal, gembal, gemsbalance, gemsbal, gbal]
    description: Sends your balance or another players.
  geco:
    usage: /geco <args>
    aliases: [economy, geco, gemeco, gemseconomy]
    description: Economy management command.
  gpay:
    usage: /gpay <user> <amount>
    aliases: [gpay, gemspay, gempay]
    description: Pay a user an amount.
  gcheque:
    usage: /gcheque
    aliases: [banknote, note, gnote, gemcheque, gemscheque]
    description: Write or Redeem cheques.